#' \code{claman} package
#'
#' Claman (Calico Lipidomics And Metabolomics ANalysis) can read .mzrollDB
#' files created using MAVEN or Quahog into an mzroll_list. These lists
#' can then be modified through normalization, signal flooring, and filtering.
#' Differential abundance analysis of metabolites can then be performed along
#' with a variety of visualizations.
#'
#' @docType package
#' @name calicomics
#' @importFrom dplyr %>%
#' @import ggplot2
NULL

## quiets concerns of R CMD check re: the .'s that appear in pipelines
utils::globalVariables(c(
  ".",
  ":=",
  ".center",
  ".entry",
  ".entry.x",
  ".entry.y",
  ".group_center",
  ".loess_fit",
  ".loess_shift",
  ".reference",
  ".reference_diff",
  "abund_mean",
  "abund_se",
  "abundance",
  "adductName",
  "anova_signif",
  "centered_log2_abundance",
  "char",
  "compoundId",
  "compoundName",
  "databaseId",
  "datetime",
  "diff_to_median",
  "displayName",
  "double_1",
  "double_2",
  "double_3",
  "double_4",
  "enrichment",
  "enrichment_plot",
  "ES",
  "FA1",
  "FA2",
  "FA3",
  "FA4",
  "fdr_summary",
  "field",
  "filename",
  "focus_pathway",
  "fgsea_results",
  "groupData",
  "groupId",
  "gsea_results",
  "gsea_table_grob",
  "id",
  "ID string entry",
  "id_string_value",
  "id_string_var",
  "lm_fits",
  "is_discovery",
  "is_focus_pathway",
  "is_tracking_sheet",
  "is_unknown",
  "label",
  "leadingEdge",
  "lipidClass",
  "log2_abundance",
  "median",
  "median_abund",
  "members",
  "method_tag",
  "MS ID string",
  "MS ID string alternative",
  "mz_delta",
  "mz_median",
  "mzmax",
  "mzmax_adj",
  "mzmin",
  "mzmin_adj",
  "mzroll_db_path",
  "mzroll_list",
  "n",
  "n_entries",
  "n_unique_records",
  "name",
  "name_tibble",
  "NES",
  "new_compoundName",
  "newSampleId",
  "nMoreExtreme",
  "num_sn_chains",
  "OH_1",
  "OH_2",
  "OH_3",
  "OH_4",
  "old_sampleId",
  "ordered_groupId",
  "ordered_sampleId",
  "one_peak_data",
  "p.value",
  "p.value.trans",
  "padj",
  "pathway",
  "pathway_enrichments",
  "pathway_entries",
  "pathway_members",
  "pathwayId",
  "pathwayName",
  "peak_label",
  "peakAreaTop",
  "peakMz",
  "plasmalogen_type",
  "position",
  "processed_mzroll",
  "pval",
  "quant_1",
  "quant_2",
  "qvalue",
  "r_position",
  "rt",
  "rt_delta",
  "rt_median",
  "rtmax",
  "rtmax_adj",
  "rtmin",
  "rtmin_adj",
  "sampleId",
  "sample description",
  "sample_label",
  "samples",
  "samples_tbl_row",
  "scaling_factor",
  "searchTableName",
  "signif_qual",
  "single_1",
  "single_2",
  "single_3",
  "single_4",
  "size",
  "sn1",
  "sn2",
  "sn3",
  "sn4",
  "sn_chains",
  "statistic",
  "sumComposition",
  "systematicCompoundId",
  "term",
  "term_data",
  "total_double",
  "total_OH",
  "total_single",
  "tube",
  "tube label",
  "type",
  "variable",
  "weights"
))
